import type { Who } from './triage';

export interface SymptomPage {
  slug: string;
  name: string; // short name used in titles
  question: string; // the search-style H1
  who: Who;
  starter: string; // prefilled into the triage box
  intro: string;
  er: string[];
  urgent: string[];
  home: string[];
}

export const SYMPTOMS: SymptomPage[] = [
  {
    slug: 'headache-and-fever',
    name: 'Headache and fever',
    question: 'Headache and fever: should I go to the ER?',
    who: 'me',
    starter: 'I have a headache and a fever',
    intro: 'A headache with a fever is most often caused by a viral infection like the flu or a cold. A few warning signs mean it needs emergency care right away.',
    er: ['A stiff neck, or pain when bending the chin to the chest', 'A rash that does not fade when you press a glass on it', 'Confusion, extreme sleepiness, or trouble waking up', 'The worst headache of your life, or one that came on in seconds', 'A seizure'],
    urgent: ['Fever above 103°F (39.4°C) that does not come down with medicine', 'Fever lasting more than 3 days', 'Painful sinuses or ear pain with the fever'],
    home: ['Rest and drink plenty of fluids', 'Use an over-the-counter fever reducer as directed on the label', 'Check your temperature every few hours and write it down'],
  },
  {
    slug: 'fever-in-child',
    name: 'Fever in a child',
    question: 'My child has a fever: when should I worry?',
    who: 'kid',
    starter: 'My child has a fever',
    intro: 'Fever is common in kids and usually means the body is fighting an infection. Age matters most: a fever in a baby under 3 months always needs a doctor right away.',
    er: ['Any fever of 100.4°F (38°C) or higher in a baby under 3 months', 'Trouble breathing, or the ribs pull in with each breath', 'Very hard to wake, limp, or not responding normally', 'A rash that does not fade when pressed', 'No wet diaper or no urine for 8 hours or more', 'A seizure'],
    urgent: ['Fever of 102°F (38.9°C) or higher in a child 3–6 months old', 'Fever lasting more than 2–3 days', 'Ear pain, sore throat, or pain when peeing'],
    home: ['Offer fluids often, even small sips', 'Dress them in light clothing', 'Use a children’s fever reducer only as the label directs for their weight and age'],
  },
  {
    slug: 'chest-pain',
    name: 'Chest pain',
    question: 'Chest pain: should I go to the ER?',
    who: 'me',
    starter: 'I have chest pain',
    intro: 'Chest pain can come from muscles, heartburn, or anxiety, but it can also be a heart attack. Treat new chest pain as an emergency until a doctor says otherwise.',
    er: ['Pressure, squeezing, or tightness in the chest', 'Pain spreading to the arm, jaw, neck, or back', 'Shortness of breath, sweating, nausea, or lightheadedness', 'Chest pain with a racing or irregular heartbeat'],
    urgent: ['Chest pain that only hurts when you press on one spot, after a strain or injury, with no other symptoms'],
    home: ['Do not wait at home with new chest pain. Call 911 if you are unsure.'],
  },
  {
    slug: 'sore-throat',
    name: 'Sore throat',
    question: 'Sore throat: is it strep, and do I need a doctor?',
    who: 'me',
    starter: 'I have a sore throat',
    intro: 'Most sore throats are caused by viruses and get better on their own within a week. Strep throat needs a test and antibiotics, so some sore throats should be checked.',
    er: ['Trouble breathing or swallowing your own spit', 'Drooling or a muffled “hot potato” voice', 'Cannot open your mouth fully'],
    urgent: ['Fever with white spots on the tonsils and no cough', 'Swollen, tender lumps in the neck', 'Sore throat lasting more than a week'],
    home: ['Warm salt-water gargles', 'Honey in warm tea for adults and children over 1 year', 'Throat lozenges and plenty of fluids'],
  },
  {
    slug: 'stomach-pain',
    name: 'Stomach pain',
    question: 'Stomach pain: when is it an emergency?',
    who: 'me',
    starter: 'I have stomach pain',
    intro: 'Stomach pain is usually from gas, indigestion, or a stomach bug. Pain that is severe, keeps getting worse, or sits in one spot can be something like appendicitis.',
    er: ['Severe pain, especially in the lower right side', 'A hard, rigid belly that hurts to touch', 'Vomiting blood or material that looks like coffee grounds', 'Black, tarry, or bloody stools', 'Pain with a fever and vomiting that will not stop', 'Pain during pregnancy'],
    urgent: ['Pain lasting more than a day', 'Pain with burning when you pee', 'Unable to keep fluids down for 12 hours'],
    home: ['Sip clear fluids', 'Eat bland foods when you feel ready', 'Avoid alcohol, caffeine, and greasy food'],
  },
  {
    slug: 'cough-that-wont-stop',
    name: 'Cough that won’t stop',
    question: 'Cough that won’t go away: when to see a doctor',
    who: 'kid',
    starter: 'Cough that won’t stop',
    intro: 'Coughs from colds can last up to 3 weeks. Watch breathing closely, especially in children.',
    er: ['Struggling to breathe, or ribs pulling in with each breath', 'Lips or face turning blue or gray', 'A high-pitched whistling sound when breathing in', 'Coughing up blood'],
    urgent: ['Cough with a fever over 102°F (38.9°C)', 'Wheezing', 'Coughing fits that end in a “whoop” or vomiting'],
    home: ['Honey for anyone over 1 year old', 'A cool-mist humidifier', 'Plenty of fluids and rest'],
  },
  {
    slug: 'rash',
    name: 'Rash',
    question: 'Rash: is it serious?',
    who: 'kid',
    starter: 'A rash',
    intro: 'Most rashes are harmless and come from viruses, heat, or skin irritation. A few rashes are warning signs of a serious infection or an allergic reaction.',
    er: ['A rash that does not fade when you press a clear glass on it, with fever', 'Swelling of the lips, tongue, or face, or trouble breathing', 'Blistering or peeling skin over a large area'],
    urgent: ['A rash with a fever', 'A painful, spreading red area that feels hot', 'A rash near the eyes'],
    home: ['Keep the skin clean and dry', 'Avoid new soaps or lotions', 'Use a cool compress for itching'],
  },
  {
    slug: 'vomiting',
    name: 'Vomiting',
    question: 'Throwing up: when to go to the ER',
    who: 'kid',
    starter: 'Throwing up',
    intro: 'Vomiting is usually from a stomach virus and passes in a day or two. The main danger is dehydration, especially in young children and older adults.',
    er: ['Signs of dehydration: no urine for 8 hours, no tears, very dry mouth, sunken eyes', 'Vomiting blood or green fluid', 'Severe belly pain', 'Vomiting after a head injury', 'Very sleepy or hard to wake'],
    urgent: ['Vomiting for more than 24 hours', 'Cannot keep any fluids down for 8 hours'],
    home: ['Wait 30–60 minutes after vomiting, then give small sips of fluid every few minutes', 'An oral rehydration drink works best', 'Slowly return to bland food'],
  },
  {
    slug: 'dizziness',
    name: 'Dizziness',
    question: 'Dizzy: should I be worried?',
    who: 'parent',
    starter: 'Dizzy when standing up',
    intro: 'Dizziness is often from standing up too fast, dehydration, or an inner-ear problem. Sudden dizziness with other new symptoms can be a sign of a stroke.',
    er: ['Face drooping, arm weakness, or trouble speaking (call 911)', 'Fainting', 'Chest pain or a racing heartbeat', 'A sudden, severe headache'],
    urgent: ['Dizziness after starting a new medicine', 'Dizziness with vomiting that will not stop'],
    home: ['Sit or lie down right away', 'Stand up slowly', 'Drink water'],
  },
  {
    slug: 'confusion-in-older-adult',
    name: 'Sudden confusion',
    question: 'My parent is suddenly confused: what should I do?',
    who: 'parent',
    starter: 'My parent is more confused than usual today',
    intro: 'Sudden confusion in an older adult is not normal aging. It can be caused by infection, dehydration, medicine, or a stroke, and should be checked quickly.',
    er: ['Confusion that came on within hours', 'Face drooping, weakness on one side, or slurred speech', 'Fever with confusion', 'Very hard to wake'],
    urgent: ['New confusion over a day or two', 'Confusion with burning urination', 'Confusion after a medicine change'],
    home: ['Do not leave them alone', 'Bring a list of all their medicines to the doctor'],
  },
  {
    slug: 'fall-in-older-adult',
    name: 'A fall',
    question: 'My parent fell: do they need the ER?',
    who: 'parent',
    starter: 'My parent fell',
    intro: 'Falls are a leading cause of injury in older adults. Head injuries and hip injuries need attention, especially in people who take blood thinners.',
    er: ['Hit their head while taking a blood thinner', 'Cannot stand or put weight on a leg', 'A leg that looks shorter or turned outward', 'Confusion, vomiting, or a bad headache after the fall', 'Passed out before or after the fall'],
    urgent: ['New pain or bruising that is getting worse', 'Hit their head with no other symptoms'],
    home: ['Watch them closely for the next 24 hours', 'Check the home for trip hazards'],
  },
  {
    slug: 'ankle-sprain',
    name: 'Ankle injury',
    question: 'Twisted ankle: sprain or broken?',
    who: 'me',
    starter: 'I twisted my ankle and it is swollen',
    intro: 'Most twisted ankles are sprains that heal with rest. An X-ray is needed if you cannot walk on it or the bone itself hurts.',
    er: ['The ankle or foot looks deformed', 'Bone is showing through the skin', 'The foot is cold, pale, or numb'],
    urgent: ['Cannot take four steps on it', 'Pain when pressing on the bony bumps of the ankle'],
    home: ['Rest, ice for 20 minutes at a time, a compression wrap, and keep it raised', 'An over-the-counter pain reliever as the label directs'],
  },
  {
    slug: 'cut',
    name: 'Cut',
    question: 'Deep cut: do I need stitches?',
    who: 'someone',
    starter: 'A deep cut on a finger',
    intro: 'Cuts that gape open, are deep, or are on the face or a joint often need stitches, ideally within a few hours.',
    er: ['Bleeding that does not stop after 10 minutes of firm pressure', 'Blood spurting', 'Numbness or cannot move the finger or limb'],
    urgent: ['The cut gapes open or is deeper than a quarter inch', 'Dirt or glass is stuck in it', 'A cut from an animal or human bite', 'No tetanus shot in the last 5 years for a dirty wound'],
    home: ['Press firmly with a clean cloth', 'Rinse with clean running water', 'Cover with a clean bandage'],
  },
  {
    slug: 'burn',
    name: 'Burn',
    question: 'Burn: when to go to the ER',
    who: 'someone',
    starter: 'A burn from a hot pan',
    intro: 'Small, red burns usually heal at home. Large burns, deep burns, and burns on the face, hands, feet, or genitals need a doctor.',
    er: ['A burn larger than the person’s palm that is blistered or white', 'Burns on the face, hands, feet, groin, or a joint', 'Chemical or electrical burns', 'Trouble breathing after smoke'],
    urgent: ['Blisters larger than a coin', 'Signs of infection: pus, spreading redness, fever'],
    home: ['Cool running water for 20 minutes', 'Do not use ice, butter, or oil', 'Cover loosely with a clean non-stick bandage'],
  },
  {
    slug: 'ear-pain',
    name: 'Ear pain',
    question: 'Ear pain: does my child need a doctor?',
    who: 'kid',
    starter: 'Ear pain',
    intro: 'Ear pain in kids is often from an ear infection after a cold. Many get better on their own in 2–3 days.',
    er: ['Swelling or redness behind the ear that pushes it forward', 'Stiff neck with fever', 'Very sleepy or hard to wake'],
    urgent: ['Fever over 102°F (38.9°C)', 'Fluid or pus draining from the ear', 'Pain lasting more than 2 days', 'Any ear pain in a baby under 6 months'],
    home: ['A warm cloth on the ear', 'A fever and pain reliever as the label directs for their weight'],
  },
  {
    slug: 'uti',
    name: 'Burning when peeing',
    question: 'Burning when I pee: is it a UTI?',
    who: 'me',
    starter: 'It burns when I pee',
    intro: 'Burning when you pee is often a urinary tract infection. UTIs usually need antibiotics, so it is worth a quick doctor or video visit.',
    er: ['High fever with shaking chills', 'Severe back or side pain with vomiting', 'Confusion in an older adult'],
    urgent: ['Fever or back pain', 'Blood in the urine', 'Symptoms during pregnancy'],
    home: ['Drink plenty of water while you arrange a visit', 'Do not hold urine in'],
  },
  {
    slug: 'allergic-reaction',
    name: 'Allergic reaction',
    question: 'Allergic reaction: when is it an emergency?',
    who: 'someone',
    starter: 'Hives after eating something new',
    intro: 'Mild allergic reactions cause itchy hives. A severe reaction, called anaphylaxis, can be life-threatening within minutes.',
    er: ['Trouble breathing, wheezing, or throat tightness', 'Swelling of the lips, tongue, or throat', 'Fainting, dizziness, or a weak pulse', 'Vomiting after a known allergen', 'Use an epinephrine auto-injector if prescribed, then call 911'],
    urgent: ['Hives spreading across the body', 'A reaction to a new medicine'],
    home: ['An over-the-counter antihistamine as the label directs', 'Avoid the trigger'],
  },
  {
    slug: 'back-pain',
    name: 'Back pain',
    question: 'Back pain: when to see a doctor',
    who: 'me',
    starter: 'Lower back pain',
    intro: 'Most back pain comes from strained muscles and improves within a few weeks. A few signs mean nerves may be affected.',
    er: ['Loss of bladder or bowel control', 'Numbness in the groin or inner thighs', 'Weakness in the legs that is getting worse', 'Back pain after a serious fall or crash'],
    urgent: ['Back pain with fever', 'Pain shooting down one leg below the knee'],
    home: ['Keep moving gently', 'Heat or ice', 'An over-the-counter pain reliever as the label directs'],
  },
  {
    slug: 'toothache',
    name: 'Toothache',
    question: 'Toothache: dentist or ER?',
    who: 'me',
    starter: 'Bad toothache',
    intro: 'A toothache usually needs a dentist, not an ER. Swelling that spreads can mean an abscess and needs care the same day.',
    er: ['Swelling spreading to the eye, neck, or under the tongue', 'Trouble swallowing or breathing', 'High fever with facial swelling'],
    urgent: ['Swelling of the gum or face', 'Fever with tooth pain'],
    home: ['Rinse with warm salt water', 'An over-the-counter pain reliever as the label directs', 'Call a dentist for the next available visit'],
  },
  {
    slug: 'pink-eye',
    name: 'Red eye',
    question: 'Red, itchy eye: is it pink eye?',
    who: 'kid',
    starter: 'Red, goopy eye',
    intro: 'Pink eye is common and usually mild. Eye pain, vision changes, or light sensitivity need a doctor quickly.',
    er: ['Sudden vision loss', 'Something hit or went into the eye with force', 'Chemical splash (rinse with water for 15 minutes first)'],
    urgent: ['Eye pain or sensitivity to light', 'Blurry vision that does not clear with blinking', 'Red eye in a contact lens wearer', 'A newborn with red, goopy eyes'],
    home: ['Wipe the eye gently with a clean, warm cloth', 'Wash hands often', 'Do not share towels'],
  },
];

export function getSymptom(slug: string) {
  return SYMPTOMS.find((s) => s.slug === slug);
}
